import { NextResponse } from "next/server";
import { getCollection } from "@/lib/mongo";

const companies = [
  {
    name: "Medway Pharmaceuticals",
    address: "12 Riverside Park, London SE10 0JF",
    location: "London, United Kingdom",
    timeZone: "Europe/London",
    standards: ["GMP", "ISO 9001", "MHRA GDP"],
  },
  {
    name: "Celtic Biologics",
    address: "4 Innovation Drive, Cardiff CF10 4BQ",
    location: "Cardiff, United Kingdom",
    timeZone: "Europe/London",
    standards: ["GMP", "ISO 13485", "EU GDP"],
  },
  {
    name: "Northern Pharma Labs",
    address: "78 Discovery Way, Newcastle NE4 7PP",
    location: "Newcastle upon Tyne, United Kingdom",
    timeZone: "Europe/London",
    standards: ["MHRA GMP", "ISO 9001", "ICH Q10"],
  },
  {
    name: "Highland Therapeutics",
    address: "15 Caledonian Park, Edinburgh EH11 3AF",
    location: "Edinburgh, United Kingdom",
    timeZone: "Europe/London",
    standards: ["EU GMP", "ISO 14001", "GxP"],
  },
  {
    name: "Beacon Clinical Supplies",
    address: "60 Meridian Road, Cambridge CB4 1TN",
    location: "Cambridge, United Kingdom",
    timeZone: "Europe/London",
    standards: ["MHRA GDP", "ISO 27001", "GMP Annex 13"],
  },
  {
    name: "Thames Valley Pharma",
    address: "22 Thames View, Reading RG1 3EU",
    location: "Reading, United Kingdom",
    timeZone: "Europe/London",
    standards: ["MHRA GMP", "ISO 9001", "ICH Q10"],
  },
  {
    name: "Midlands Biotech",
    address: "8 Science Park, Birmingham B15 1TP",
    location: "Birmingham, United Kingdom",
    timeZone: "Europe/London",
    standards: ["GMP", "ISO 13485", "MHRA GDP"],
  },
  {
    name: "Bristol Pharma Group",
    address: "30 Avon Street, Bristol BS2 0PS",
    location: "Bristol, United Kingdom",
    timeZone: "Europe/London",
    standards: ["EU GMP", "ISO 9001", "GxP"],
  },
  {
    name: "Mersey Therapeutics",
    address: "14 Dockside Way, Liverpool L3 1BY",
    location: "Liverpool, United Kingdom",
    timeZone: "Europe/London",
    standards: ["MHRA GMP", "ISO 14001", "GMP Annex 13"],
  },
  {
    name: "Solent Clinical Research",
    address: "5 Maritime Gate, Southampton SO14 3TL",
    location: "Southampton, United Kingdom",
    timeZone: "Europe/London",
    standards: ["MHRA GDP", "ISO 27001", "ICH Q10"],
  },
  {
    name: "Oxfordshire Biopharma",
    address: "40 Innovation Way, Oxford OX4 2XQ",
    location: "Oxford, United Kingdom",
    timeZone: "Europe/London",
    standards: ["GMP", "ISO 13485", "GxP"],
  },
  {
    name: "Kent Pharma Services",
    address: "18 Canterbury Road, Maidstone ME14 4AA",
    location: "Maidstone, United Kingdom",
    timeZone: "Europe/London",
    standards: ["MHRA GDP", "ISO 9001", "EU GMP"],
  },
  {
    name: "Surrey Clinical Labs",
    address: "9 Research Lane, Guildford GU2 7XH",
    location: "Guildford, United Kingdom",
    timeZone: "Europe/London",
    standards: ["GMP", "ISO 17025", "ISO 9001"],
  },
  {
    name: "Sussex Pharma Partners",
    address: "16 Coastal Park, Brighton BN1 4QS",
    location: "Brighton, United Kingdom",
    timeZone: "Europe/London",
    standards: ["MHRA GMP", "ISO 14001", "ICH Q10"],
  },
  {
    name: "Hampshire Pharma Solutions",
    address: "11 Test Valley Way, Winchester SO23 9EL",
    location: "Winchester, United Kingdom",
    timeZone: "Europe/London",
    standards: ["EU GMP", "ISO 9001", "GMP Annex 13"],
  },
  {
    name: "Lancashire Biologics",
    address: "3 Ribble Park, Preston PR1 8QF",
    location: "Preston, United Kingdom",
    timeZone: "Europe/London",
    standards: ["MHRA GDP", "ISO 13485", "GxP"],
  },
  {
    name: "Yorkshire Pharma Works",
    address: "27 Aire Street, Leeds LS1 4HT",
    location: "Leeds, United Kingdom",
    timeZone: "Europe/London",
    standards: ["GMP", "ISO 9001", "ICH Q10"],
  },
  {
    name: "Tyne Wear Pharma",
    address: "19 Quayside, Sunderland SR1 1SJ",
    location: "Sunderland, United Kingdom",
    timeZone: "Europe/London",
    standards: ["MHRA GMP", "ISO 27001", "EU GDP"],
  },
  {
    name: "Belfast Pharma Manufacturing",
    address: "25 Lagan Road, Belfast BT1 5GS",
    location: "Belfast, United Kingdom",
    timeZone: "Europe/London",
    standards: ["EU GMP", "ISO 9001", "GMP Annex 13"],
  },
  {
    name: "Glasgow Pharma Works",
    address: "31 Clyde Street, Glasgow G1 4PS",
    location: "Glasgow, United Kingdom",
    timeZone: "Europe/London",
    standards: ["MHRA GDP", "ISO 14001", "GxP"],
  },
  {
    name: "Aberdeen Pharma Supply",
    address: "7 Granite Way, Aberdeen AB10 1AQ",
    location: "Aberdeen, United Kingdom",
    timeZone: "Europe/London",
    standards: ["GMP", "ISO 9001", "ICH Q10"],
  },
  {
    name: "Dundee Pharma Labs",
    address: "13 Tay View, Dundee DD1 4HT",
    location: "Dundee, United Kingdom",
    timeZone: "Europe/London",
    standards: ["MHRA GMP", "ISO 13485", "EU GMP"],
  },
  {
    name: "Leeds Clinical Supplies",
    address: "21 Innovation Row, Leeds LS2 3AA",
    location: "Leeds, United Kingdom",
    timeZone: "Europe/London",
    standards: ["MHRA GDP", "ISO 9001", "GxP"],
  },
  {
    name: "Manchester Biotech Group",
    address: "55 Oxford Road, Manchester M1 6EU",
    location: "Manchester, United Kingdom",
    timeZone: "Europe/London",
    standards: ["GMP", "ISO 27001", "ICH Q10"],
  },
  {
    name: "Liverpool Pharma Services",
    address: "10 Baltic Square, Liverpool L1 0AN",
    location: "Liverpool, United Kingdom",
    timeZone: "Europe/London",
    standards: ["EU GMP", "ISO 9001", "GMP Annex 13"],
  },
  {
    name: "Sheffield Therapeutics",
    address: "6 Steelhouse Lane, Sheffield S1 2GG",
    location: "Sheffield, United Kingdom",
    timeZone: "Europe/London",
    standards: ["MHRA GMP", "ISO 13485", "GxP"],
  },
  {
    name: "Nottingham Pharma Labs",
    address: "14 Lace Market, Nottingham NG1 1QE",
    location: "Nottingham, United Kingdom",
    timeZone: "Europe/London",
    standards: ["GMP", "ISO 9001", "ICH Q10"],
  },
  {
    name: "Leicester Biopharma",
    address: "28 Jubilee Way, Leicester LE1 3PJ",
    location: "Leicester, United Kingdom",
    timeZone: "Europe/London",
    standards: ["MHRA GDP", "ISO 14001", "GMP Annex 13"],
  },
  {
    name: "Reading Clinical Manufacturing",
    address: "72 Kennet Road, Reading RG1 8BD",
    location: "Reading, United Kingdom",
    timeZone: "Europe/London",
    standards: ["EU GMP", "ISO 9001", "GxP"],
  },
  {
    name: "Milton Keynes Pharma",
    address: "9 Vantage Park, Milton Keynes MK9 3DL",
    location: "Milton Keynes, United Kingdom",
    timeZone: "Europe/London",
    standards: ["MHRA GMP", "ISO 27001", "ICH Q10"],
  },
  {
    name: "Cambridge Therapeutics Hub",
    address: "44 Genome Way, Cambridge CB2 0QT",
    location: "Cambridge, United Kingdom",
    timeZone: "Europe/London",
    standards: ["GMP", "ISO 13485", "GMP Annex 13"],
  },
  {
    name: "Durham Pharma Supply",
    address: "5 Cathedral View, Durham DH1 4BQ",
    location: "Durham, United Kingdom",
    timeZone: "Europe/London",
    standards: ["MHRA GDP", "ISO 9001", "GxP"],
  },
  {
    name: "Worcester Pharma Group",
    address: "18 Severn Street, Worcester WR1 2NE",
    location: "Worcester, United Kingdom",
    timeZone: "Europe/London",
    standards: ["EU GMP", "ISO 14001", "ICH Q10"],
  },
  {
    name: "Bath Biologics",
    address: "26 Crescent Lane, Bath BA1 2RQ",
    location: "Bath, United Kingdom",
    timeZone: "Europe/London",
    standards: ["GMP", "ISO 9001", "MHRA GDP"],
  },
  {
    name: "Exeter Clinical Pharma",
    address: "33 Quay Road, Exeter EX2 4AN",
    location: "Exeter, United Kingdom",
    timeZone: "Europe/London",
    standards: ["MHRA GMP", "ISO 27001", "GMP Annex 13"],
  },
  {
    name: "Plymouth Pharma Supply",
    address: "12 Ocean Gate, Plymouth PL1 2PS",
    location: "Plymouth, United Kingdom",
    timeZone: "Europe/London",
    standards: ["EU GMP", "ISO 9001", "GxP"],
  },
  {
    name: "Brighton Biotech",
    address: "7 Pavilion Street, Brighton BN2 1RA",
    location: "Brighton, United Kingdom",
    timeZone: "Europe/London",
    standards: ["GMP", "ISO 13485", "ICH Q10"],
  },
  {
    name: "Portsmouth Pharma Logistics",
    address: "20 Harbour View, Portsmouth PO1 3TY",
    location: "Portsmouth, United Kingdom",
    timeZone: "Europe/London",
    standards: ["MHRA GDP", "ISO 9001", "GMP Annex 13"],
  },
  {
    name: "Newport Pharma",
    address: "14 Usk Way, Newport NP20 1HG",
    location: "Newport, United Kingdom",
    timeZone: "Europe/London",
    standards: ["MHRA GMP", "ISO 14001", "GxP"],
  },
  {
    name: "Luton Pharma Services",
    address: "6 Capability Green, Luton LU1 3PE",
    location: "Luton, United Kingdom",
    timeZone: "Europe/London",
    standards: ["GMP", "ISO 9001", "ICH Q10"],
  },
];

export async function POST() {
  const collection = await getCollection("companies");
  const now = new Date();

  const operations = companies.map((company) => ({
    updateOne: {
      filter: { name: company.name },
      update: {
        $set: { ...company, updatedAt: now },
        $setOnInsert: { createdAt: now },
      },
      upsert: true,
    },
  }));

  const result = await collection.bulkWrite(operations, { ordered: false });

  return NextResponse.json({
    upserted: result.upsertedCount,
    modified: result.modifiedCount,
    matched: result.matchedCount,
  });
}
